allow to pass a uri via editor config and model update
TypeFox/monaco-components pull request #29
Opened 2023-07-21 07:25 UTC by ChristophKuper

2023-07-21 07:51 UTC, kaisalmen commented
@ChristophKuper thank you very much. This looks good. Do you want to alter one of the existing examples to demonstrate this?

2023-07-21 11:15 UTC, ChristophKuper commented
@kaisalmen okay i adjusted the example. i also aligned some variables to be more clear while switching between code & original code

2023-07-21 13:19 UTC, kaisalmen reviewed
Looking good. Introducing `ModelUpdate` is a good idea. Only problem I found when testing with GitPod is that **Swap Code** does not work when "Diff View" is shown:
![image](https://github.com/TypeFox/monaco-components/assets/21079138/cbb8d090-1903-4ab6-85fd-c30ddfeb11fe)

2023-07-21 13:32 UTC, kaisalmen commented
⬆️ `updateDiffModel` has to be used here instead of `updateModel`. Thanks

2023-07-24 07:30 UTC, ChristophKuper commented
@kaisalmen thx i quickly fixed the linting and allowed also updating in case a diff editor is open.

2023-07-24 07:51 UTC, kaisalmen requested changes
Just this method extraction and then this is ready for merge. Thank you.

2023-07-24 07:51 UTC, kaisalmen commented on packages/monaco-editor-wrapper/src/editor.ts
> +        if (modelUpdate.code !== undefined) {
One last thing: Please extract these checks into a separate function, then it can be used by `updateModel` and `updateDiffModel`.

2023-07-24 09:19 UTC, kaisalmen approved these changes
Thank you very much, LGTM! 🎉

2023-07-24 09:21 UTC, merged

2023-07-27 10:18 UTC, kaisalmen commented
@ChristophKuper I just released new npm packages. Forgot to do this.